<?php


namespace App\Views;

use Core\View;

class Footer extends View
{
    public function __construct()
    {
        parent::__construct($this->render());
    }

//    public function generate()
//    {
//        $nav = [App::$router::getUrl('index') => 'Titulinis'];
//    }

    public function render($template_path = ROOT . '/app/templates/footer.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }
}